---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Set /etc/localtime link
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ common_timezone }}"
    dest: /etc/localtime
    state: link
    force: true

- name: Set /etc/timezone content
  ansible.builtin.copy:
    dest: /etc/timezone
    content: "{{ common_timezone }}\n"
    mode: "0644"
