---
- name: restart app container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ docker_image }}:{{ docker_image_tag }}"
    state: started
    restart: true
    restart_policy: "{{ app_restart_policy }}"
    ports:
      - "{{ app_port }}:5000"
    env: "{{ app_environment }}"
